#!/usr/bin/env bash
set -eo pipefail
if TEXTO=$(grim -g "$(slurp)" - | tesseract -c debug_file=/dev/null -l por - -); then
  printf '%s\n' "$TEXTO" | wl-copy
  notify-send -a 'Text Grab de Taubaté' -- "$TEXTO"
fi
