#!/bin/sh
ETERNAL=${1:-September 7 1993}
ETERNAL_DAY_ONE=$(date -d "$ETERNAL" +'%Y/%m/01')
ETERNAL_EPOCH=$(date -d "$ETERNAL_DAY_ONE" +'%s')
NOW_EPOCH=$(date ${2+-d "$1"} +'%s')

LANG=en_US.UTF8 date -d "$ETERNAL" +"%B $(( (NOW_EPOCH-ETERNAL_EPOCH+86400) / 86400 )), %Y"
